config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'
  
  resources :employees
  
  post   'activity/new', to: 'activity#new'
end

app/models/activity.rb
class Activity < ApplicationRecord
  before_save :update_check_in
  belongs_to :employee
  
  def update_check_in
    activity = Activity.where(employee_id: self.employee_id)
    if activity.length > 0
      self.check_in = activity.last.check_in == true ? false:true
    else
      self.check_in = true
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :activities
  validates :name, presence: true,
                   length: { minimum: 6  }
  validates :password, presence: true,
                   length: { minimum: 10  }
  has_secure_password
  
  
  def Employee.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def new
    if logged_in?
      new_activity = Activity.new(employee_id: session[:employee_id], check_in: true)
      new_activity.save
      redirect_to current_employee
    else
      redirect_to login_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include ActivityHelper
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
  end
  
  def index
    if logged_in?
      if current_employee.admin?
        @employees = Employee.all
      else
        redirect_to current_employee
      end
    else
      redirect_to login_path
    end
  end
  
  def show
    if logged_in?
      if params[:id] == session[:employee_id].to_s
        @employee = Employee.find_by(id: session[:employee_id])
        @next_activity = get_next_activity @employee
        @activities = get_activities @employee
      else
        if current_employee.admin?
          @employee = Employee.find_by(id: params[:id])
          if @employee.nil?
            redirect_to current_employee
          else
            @next_activity = get_next_activity @employee
            @activities = get_activities @employee
          end
        else
          redirect_to current_employee
        end
      end
    else
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to current_employee
    else
      render 'new'
    end
  end
  
  def create
    employee = Employee.find_by(id: params[:session][:id])
    if employee && employee.authenticate(params[:session][:password])
      flash[:success] = 'Successfully Logged In!'
      log_in(employee)
      redirect_to employee
    else
      flash.now[:danger] = 'Incorrect Login Credentials'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      redirect_to current_employee
    else
      render 'static_pages/home'
    end
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
  def get_next_activity(employee)
    next_activity = Activity.where(employee_id: employee.id).last.check_in == false ? 'Check In' : 'Check Out'
    return next_activity
  end
  
  def get_activities(employee)
    if employee.admin?
      emp_activities = Employee.includes(:activities)
      activities = restructure_activities(emp_activities)
      activities = activities.sort_by { |activity| activity['updated_at'] }
    else
      emp_activities = Employee.includes(:activities).where(id: employee.id)
      activities = restructure_activities(emp_activities)
    end
    return activities
  end
  
  def restructure_activities(emp_activities)
    activities = Array.new()
    for emp in emp_activities
      for activity in emp.activities
        activities.push({
          "id" => emp.id,
          "name" => emp.name,
          "check_in" => activity.check_in == true ? "Checked In" : "Checked Out",
          "updated_at" => activity.updated_at
        })
      end
    end
    return activities
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(employee)
    session[:employee_id] = employee.id
  end
  
  def current_employee
    @current_employee ||= Employee.find_by(id: session[:employee_id])
  end
  
  def logged_in?
    !current_employee.nil?
  end
  
  def log_out
    session.delete(:employee_id)
    @current_employee = nil
  end
  
  def admin_access?
    if current_employee.nil?
      return false
    else
      if current_employee.admin? && (params[:id] != session[:employee_id].to_s)
        return true
      else
        return false
      end
    end
    # current_employee.nil? || (current_employee.admin? && (params[:id] != session[:employee_id].to_s))
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/activity/new.html.erb
<h1>Activity#new</h1>
<p>Find me in app/views/activity/new.html.erb</p>

app/views/employees/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Employee ID</th>
        <th scope="col">Activity Name</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= link_to employee.id, employee  %></td>
          <td><%= link_to employee.name, employee %></td>
        </tr>
      <% end  %>
    </tbody>
  </table>
</div>

app/views/employees/new.html.erb
<h1>Employees#new</h1>
<p>Find me in app/views/employees/new.html.erb</p>

app/views/employees/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @employee.name %>
        <% if @employee.admin?  %>
            (Admin)
        <% end  %>
      </h1>
    </section>
  </aside>
</div>
<% if !admin_access? %>
  <div class="row">
    <div class="container">
        <%= link_to @next_activity, activity_new_path, :method=> :post, class: "activity-btn btn btn-primary" %>
    </div>
  </div>
<% end  %>
<div class="row">
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Employee</th>
          <th scope="col">Activity</th>
          <th scope="col">Time</th>
        </tr>
      </thead>
      <tbody>
        <% @activities.each do |activity| %>
          <tr>
            <td><%= link_to activity['name'], employee_path(activity['id']) %></td>
            <td><%= activity['check_in'] %></td>
            <td><%= activity['updated_at'] %></td>
          </tr>
        <% end  %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_back_to_home.html.erb
<% if admin_access?  %>
  <div class="row">
    <%= link_to "Back to Home", current_employee  %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in?  %>
      <%= link_to "Flock App", current_employee, id: "logo" %>
    <%  else %>
      <%= link_to "Flock App", root_path, id: "logo" %>
    <%  end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in?  %>
          <% if current_employee.admin?  %>
            <li><%= link_to "View Employees", '/employees' %></li>
            <li><%= link_to "View Activity", current_employee %></li>
          <% end  %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
        <% else  %>
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <%  end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flock App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'  %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= render 'layouts/back_to_home'  %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Flock App</h1>

  <h2>
    This is the home page for the Flock Coding Challenge by Calvin Gomez
  </h2>

  <%= link_to "Employee Login", login_path, class: "btn btn-lg btn-primary" %>
</div>